### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by JoubaMety** [JoubaMety/notes.joubamety.com#1]
lazy To-Do list for poor people

- [ ] yt-videowithsubs.ps1
- [ ] Pixel Format, Color Format, Color Space, HDR... whatever else
- [ ] Yuv420p vs Yuv444p
  - Test: 1/1 res yuv420p vs 1/4 res yuv444p
- [ ] 8-bit vs 10-bit Banding
- [ ] H264 Baseline vs Main vs High perfomance
- [ ] Most Compatible H264+AAC for iPhone users (and also Android users somehow)
- [ ] Video player's viewing of 24 FPS content on 60 Hz display - Details

**Comment by WoMspace** [comment]
yuv410p

**Comment by xeome** [comment]
Fix your bootloader, kitten 
![image](https://github.com/JoubaMety/notes.joubamety.com/assets/44901648/da75eba4-cbb5-48c7-b9fc-0b889d92a40d)

**Comment by WoMspace** [comment]
dark color banding and blocking
10-bit color
![](https://cdn.discordapp.com/emojis/1097424271892033617.webp)

**Comment by WoMspace** [comment]
no you fek theyre separate things, 10bit might just be one possible solution
